### ISSUE TITLE
Static size grids (unaffected by zoom) 

### ISSUE THREAD

**Issue by knownasilya** [patrickarlt/leaflet-virtual-grid#4]
@patrickarlt thanks for pointing out your library.

I'm trying to make an implementation of "fog of war" as a layer. Basically I need the grids to be a fixed size so that I can toggle the area as "visited", and then generate a canvas layer based on that data. I'm not sure how exactly it'll work, but will take any advice.

P.S. this request might be outside of the scope of this library..

**Comment by patrickarlt** [comment]
@knownasilya I spend a little time trying to figure this out this evening. I don't really think this will be possible at least in the scope of this library. Most of this is because this (like TileLayer, ect...) uses the pixel bounds of the map to generate the coordinates. https://github.com/patrickarlt/leaflet-virtual-grid/blob/master/src/virtual-grid.js#L94 whoch in turn relies on the pixel size of the map https://github.com/Leaflet/Leaflet/blob/v0.7.7/src/map/Map.js#L385-L388.

I couldn't really figure out a decent way to do this in a nice simple way.

I don't really know what your data structure or requirements are but querying something like RBush for every cell isn't actually very intensive and is pretty performant. In Esri Leaflet I take things a little farther and wrap the drawing of features that come down from the server in `requestAnimationFrame` https://github.com/Esri/esri-leaflet/blob/master/src/Layers/FeatureLayer/FeatureManager.js#L103-L106 too keep things running smoothly.

This might be a potential path for you to take.

1. Cache all your fog-of-war data in RBush
2. Whenever a well is created or added hit Rbush for the data
3. Inside requestAnimationFrame generate canvas that represents the fog of war data for a cell.
4. Use `L.ImageOverlay` with your data to place the generated tile.

This is a little excessive though. You could probably just use `L.GridLayer` and create your canvas tiles dynamically. `gridLayer._tileCoordsToBounds` will let you turn the x/y/z coords to bounds and then you can cut out a lot of the logic from my flow above. The code probably looks something like this:

```js
var FogOfWarLayer = L.GridLayer.extend({
  createTile (coords) {
    // I think this method should be public. I'll probably open an issue about it soon.
    var bounds = this._tileCoordsToBounds(coords);
    // query RBush for data return a canvas
    return document.createElement('canvas');
  }
});
```

And your done. Leaflet also will take care of zoom logic redrawing ect. So it is probably a much better option then trying to figure out a static sized grid.

**Comment by patrickarlt** [comment]
I'm going to close this since I think the solution you should look at first is to just extend `L.GridLayer` and see if it works. If that doesn't work out I'll take another look at this and see if I can work something out again.

**Comment by knownasilya** [comment]
Thanks for your suggestions @patrickarlt! Really appreciate it.
